### ISSUE TITLE
Support vor Angular v15

### ISSUE THREAD

**Issue by mii-shell** [Danieliverant/ng-dl#10]
Update library from Angular v14 to Angular v15 so that this lib can be used in an Angular v15 project without npm complaining about conflicting peer dependencies

**Comment by Danieliverant** [comment]
@webmichelle thanks, done.
please install the @leatest version of the needed package and close this issue if it's fixed the warnings :)

**Comment by mii-shell** [comment]
@Danieliverant Thanks for the quick update! :)

Unfortunately the issue still exists. This is probably because the `utils` and  `delayed-dragover` projects, which are used here, are still depending on v14, as I can see from their `package.json` file

**Comment by Danieliverant** [comment]
> 

@webmichelle 
Right, sorry, please try again

**Comment by mii-shell** [comment]
@Danieliverant Now it works perfectly fine. Thanks! :)
