### ISSUE TITLE
"Enter" is not allowed when is pressed

### ISSUE THREAD

**Issue by jrpedrianes** [Danieliverant/ng-dl#4]
Due to the directive is capturing all the "key down" events, when we press "enter" (code  13) the directive is capturing it.

For example, this event is required if we want to submit a form when the enter is pressed.

**Comment by liverant** [comment]
Thanks! @jrpedrianes 
fixed in [v3.0.1](https://www.npmjs.com/package/@ng-dl/numeric-input/v/3.0.1)
please update.

closing.
