### ISSUE TITLE
Enabling comman with inputmode="decimal"

### ISSUE THREAD

**Issue by FireSon** [Danieliverant/ng-dl#7]
Hi,

I tried to follow your example in Blazor, but I still am not able to use the comma with inputmode="decimal" on a mobile device. Did you find a way around that?

Thanks!

**Comment by liverant** [comment]
> Hi,
> 
> I tried to follow your example in Blazor, but I still am not able to use the comma with inputmode="decimal" on a mobile device. Did you find a way around that?
> 
> Thanks!

Hi! Please add a code example (including the Module, provider, and the HTML containing the input)
And on what device?

**Comment by Danieliverant** [comment]
@FireSon please add an example or I will have to close this issue
