### ISSUE TITLE
numeric-input: ERROR TypeError: Cannot read properties of undefined (reading 'value')

### ISSUE THREAD

**Issue by arturgawlik** [Danieliverant/ng-dl#8]
When locale are set as 'pl' the ` ERROR TypeError: Cannot read properties of undefined (reading 'value')` in library is thown.
Minimal reproduction: https://stackblitz.com/edit/angular-ivy-ojdzhr?file=src/app/app.module.ts 
It's because there is no group prop for:
`Intl.NumberFormat('pl', { useGrouping: true }).formatToParts(1234.5)` called in: https://github.com/Danieliverant/ng-dl/blob/c7259d5c4dc6cbf66b296fa906977562b539691d/projects/numeric-input/src/lib/locale.service.ts#L31 

This can be fix by using `12345.6` insted of `1234.5`

**Comment by Danieliverant** [comment]
@arturgawlik 
Thank you, fixed in [v3.0.3](https://github.com/Danieliverant/ng-dl/compare/v3.4.1...v3.5.0)

PRs are always welcome :-)
