### ISSUE TITLE
Numeric input directive bug - seperator "jumps back" after edit

### ISSUE THREAD

**Issue by matthiasvop** [Danieliverant/ng-dl#9]
Using the default codeSandbox example, but changing the locale to de-de seems to work fine at first, accepting `,` as decimal seperator.

When focus leaves the input field, the field "returns" to using `.` as decimal separator - creating quite confusing behavior (the user inputs one thing, and then sees something else).

![2023-01-16_15h21_29](https://user-images.githubusercontent.com/92366903/212704651-0806d358-5081-4f4a-80c6-146ba4b6e349.gif)

my expectation was that this would fully transition the input-field to use "," (the german decimal separator) (both in visualization and input) - while still returning the number counterpart as part of the form-field binding.

**Comment by Danieliverant** [comment]
Hi @matthiasvop, what you are asking is not possible, the browsers will always render numeric fields with a dot, my directive can only allow the user to enter other decimal separators that the browser will accept, but will convert it to a dot.

You can use input-mask solution to solve your issue, maybe in the future I will prepare my own input-mask solution that will use the same logic this directive uses.

Closing for now.
